### ISSUE TITLE
Allow temporary commands

### ISSUE THREAD

**Issue by kensanata** [kensanata/bitlbee#11]
I'd like to temporarily block and mute accounts and hashtags. A timer – or a restart – should undo the command after 24h, for example. We wouldn't save this state, so if bitlbee is restarted, this state is lost.

**Comment by WPettersson** [comment]
Sorry just to be pestering, but if you are considering this, I've always wanted the ability to also schedule other actions at later times. In particular, re-toots/tweets, which means storing the ID of the toot/tweet. This feels like it might be similar to a temporary blocking/muting, as that's also a future action that needs some information (a username). Could be it's completely different though, just wanted to throw it out there.

**Comment by kensanata** [comment]
I totally agree. Maybe a command prefix would do: "later". So you could "later post I'm offline and still posting" or "later unblock kensanata". Now I want to use the syntax allowed by [at](https://en.wikipedia.org/wiki/At_(Unix)). I'm a bit worried about a job list, though. Ideally, I'd only give every user a fixed number of slots, say three, or ten. Otherwise the queue is a way to make bitlbee run out of memory.
